name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ] # Test against multiple PHP versions
  
    steps:
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --coverage-text
